version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini

# replicate-start 1
  # ID=index
  clientID:
    # ID=index
    container_name: clientID
    image: client:latest
    entrypoint: /client
    environment:
      # N=index
      - CLI_ID=N
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        # N=index
        source: ./client/datasets/agency-N.csv
        target: /bets.csv

# replicate-end
  test_server:
    profiles: ["test_server"]
    container_name: test_server
    image: alpine:latest
    entrypoint: /bin/sh /test.sh
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./test_server.sh
        target: /test.sh

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
